version: "3.9"
services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_HOST: db
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  webserver:
    image: nginx:1.21
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./php/src:/var/www/html
    depends_on:
      - app
volumes:
  db-data:
